version: "2"

services:
  mysqldb:
    image: mysql:$MYSQL_VERSION
    container_name: $MYSQL_NAME
    ports:
      - "${HOST_MYSQL_PORT}:3306"
    volumes:
      - ./db-backups:/var/mysql/backups
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    restart: always
  web:
    build: .
    container_name: $WEB_NAME
    volumes:
      - ./docroot:/var/www/html
      - ./config:$CONFI_DIRECTORY
    ports:
      - "${HOST_APACHE_PORT}:80"
volumes:
  db-data:
